[database]
    tokenkey = ''
    database_id = ''

[propnames]
    # Property Names
    ## bib name = property name
    ## Check bib names: https://ja.wikipedia.org/wiki/BibTeX
    ## Note that bib names will be used as lower case
    doi = 'DOI'
    author = 'Authors'
    title = 'Title'
    edition = 'Edition'
    year = 'Year'
    journal = 'Journal'
    volume = 'Volume'
    pages = 'Pages'
    publisher = 'Publisher'
    id = 'Citekey'
    entrytype = 'Type'
    howpublished = 'HowPublished'

    # Other property
    output_target = 'Cite in'
    pdf = 'PDF'

[abbr]
    #  Specification of abbreviation
    'Full Name' = 'Abbreviated'
    'PLOS ONE' = 'PLOS ONE'

[grobid]
    server = ''  # Keep it empty if you do not wanna extract fulltext
    # server = 'https://kermitt2-grobid.hf.space'  # Demo server provided by GROBID developer, no use too much!

[misc]
    # Directory to save bib files
    dir_save_bib = ''
    upload_pdf = true
